name: example
on: push
jobs:
  build_skim:
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build
        run: |-
          COMPILER="$(root-config --cxx)"
          FLAGS="$(root-config --cflags --libs)"
          # shellcheck disable=SC2086
          "$COMPILER" -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
      - uses: actions/upload-artifact@v3
        with:
          name: skim6.26.10-conda
          path: skim
  skim:
    needs: build_skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: skim6.26.10-conda
      # - name: access control
      #   run: printf "${{ secrets.USER_PASS }}" | base64 -d | kinit "${{ secrets.USER_NAME }}@vt.edu"
      - name: skim
        run: |
          chmod +x ./skim
          ./skim root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/GluGluToHToTauTau.root skim_ggH.root 19.6 11467.0 0.1 > skim_ggH.log
      - uses: actions/upload-artifact@v3
        with:
          name: skim_ggH
          path: |
            skim_ggH.root
            skim_ggH.log
  plot:
    needs: skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: skim_ggH
      - name: histogram
        run: python histograms.py skim_ggH.root ggH hist_ggH.root
      - uses: actions/upload-artifact@v3
        with:
          name: histograms
          path: hist_ggH.root
  test_ggH:
    needs:
      - plot
      - skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Download from skim
        uses: actions/download-artifact@v3
        with:
          name: skim_ggH
      - name: Download from plot
        uses: actions/download-artifact@v3
        with:
          name: histograms
      - name: test_cutflow_ggH
        run: python tests/test_cutflow_ggH.py
      - name: test_plot_ggH
        run: python tests/test_plot_ggH.py
