name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  build_skim:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:${{ matrix.version }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        version: ['6.26.10-conda']
        allow_failure: [false]
        include:
          - version: 'latest'
            allow_failure: true
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build
        run: |-
          COMPILER="$(root-config --cxx)"
          FLAGS="$(root-config --cflags --libs)"
          # shellcheck disable=SC2086
          "$COMPILER" -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
      - uses: actions/upload-artifact@v3
        with:
          name: skim${{ matrix.version }}
          path: skim
  skim:
    needs: build_skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: skim6.26.10-conda
      # - name: access control
      #   run: printf "${{ secrets.USER_PASS }}" | base64 -d | kinit "${{ secrets.USER_NAME }}@vt.edu"
      - name: skim
        run: |
          chmod +x ./skim
          ./skim root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/GluGluToHToTauTau.root skim_ggH.root 19.6 11467.0 0.1
